services:

  postgres-db:
    image: postgres:15-alpine
    container_name: jenkins_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jenkins_demo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - jenkins-net

  jenkins-demo-app:
    image: ornsunlang/jenkins-demo:${IMAGE_TAG:-latest}
    container_name: jenkins-app
    ports:
      - "8080:1200"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      postgres-db:
        condition: service_healthy
    restart: always
    networks:
      - jenkins-net

volumes:
  postgres_data:

networks:
  jenkins-net:
    name: jenkins-net
    external: true