services:
  jenkins-demo-app:
    image: ornsunlang/jenkins-demo:${IMAGE_TAG:-latest}
    container_name: jenkins-demo-app
    ports:
      - "8080:1200"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always